name: GH Pages Deploy

on:
  push:
    branches: [master]
    paths:
      - 'plugins/**'
      - 'site/**'
  pull_request:
    branches: [master]
    paths:
      - 'plugins/**'
      - 'site/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Generate pages from plugin JSON
        run: uv run .github/generate_site_content.py

      - name: Build site 🏗️
        run: uvx marmite site html -vvvv --url 'https://plugins.danklinux.com/'

      - name: List files on site 📂
        run: ls -R html

      - name: Upload artifact 📦
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'html'

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Pages 📄
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4

