name: GH Pages Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Generate pages form plugin JSON
        run: uv run .github/generate_site_content.py

      - name: Build site 🏗️
        run: uvx marmite site html -vvvv --url 'https://plugins.danklinux.com/'

      - name: List files on site 📂
        run: ls -R html

      - name: Setup Pages 📄
        if: github.event_name == 'push'
        uses: actions/configure-pages@v5

      - name: Upload artifact 📦
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'html'

      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4
